# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SKRestaurant_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SKRestaurant_iOS

  pod 'Alamofire', '~> 5.6.2'
  pod 'IQKeyboardManagerSwift', '~> 6.5.10'
  pod 'HandyJSON', '~> 5.0.2'
  pod 'SwiftyJSON', '~> 5.0.1'
  pod 'CryptoSwift', '~> 1.6.0'
  pod 'ProgressHUD', '~> 13.6'
  
end
